// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4v575dHtB41myE6YhL65bETXf9DlNgNY',
    appId: '1:322050401774:web:0e66e0ee2cafb37e4e9aff',
    messagingSenderId: '322050401774',
    projectId: 'social-app-48924',
    authDomain: 'social-app-48924.firebaseapp.com',
    storageBucket: 'social-app-48924.firebasestorage.app',
    measurementId: 'G-FC1CZM0TEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCal82i8k-i11mha3jg26zXaKJ6zCHkwK0',
    appId: '1:322050401774:android:96d7c7ce79d783404e9aff',
    messagingSenderId: '322050401774',
    projectId: 'social-app-48924',
    storageBucket: 'social-app-48924.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH9AvTkdvXyPVy6rihtZ7ButahJiZOhtg',
    appId: '1:322050401774:ios:767e0661bd47abb24e9aff',
    messagingSenderId: '322050401774',
    projectId: 'social-app-48924',
    storageBucket: 'social-app-48924.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );
}
